version: '3'
services: 
  web: 
    # Below needed for when using custom docker file
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  # tests: 
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes: 
  #     - /app/node_modules
  #     - .:/app
  #   #overwrites the command in the docker file
  #   command: ["npm", "run", "test"]
